### ISSUE TITLE
How to add 3D model to Sketchfab

### ISSUE THREAD

**Issue by malenenielsen** [UNISvalbard/Geo-SfM#20]
1. Create a profile on Sketchfab.com
2. Go to settings --> password & API
3. Copy API token. This makes you able to upload 3D models from exporters & other applications directly to your account.
4. Go to your 3D model in Agisoft Metashape
5. Choose file --> Upload data
6. Choose Sketchfab and paste the API token into the API key field. Give your model a title and a short description. Press OK.

Your model should now appear in Sketchfab! :)

**Comment by PeterBetlem** [comment]
@nilrodes This should probably be included somewhere still. Perhaps a new session on publishing? Section could include V3Geo and Sketchfab?

**Comment by nilrodes** [comment]
Done! I pushed it to GitHub. If you think it is good enough, you can publish it :)
