### ISSUE TITLE
Issue on page https://unisvalbard.github.io/Geo-SfM/content/lessons/l1/tutorial.html#build-dense-cloud

### ISSUE THREAD

**Issue by 247rocketman** [UNISvalbard/Geo-SfM#23]
The function "build dense cloud" has been renamed to simply "build point cloud".
![image](https://user-images.githubusercontent.com/126167227/229148362-3ac75685-0d36-42df-97bf-bbb8f67761fc.png)

**Comment by PeterBetlem** [comment]
Thank you! This is indeed the case; and has been for a while since we updated to v2.0.0. The recent updates should reflect this change.
